name: Default parser tests

on:
  push:
    paths:
      - parser-default/**
      - .github/workflows/tests-parser-default.yml
      - .github/workflows/tests.yml
  workflow_dispatch:

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
    with:
      package: parser-default
