name: ICU parser tests

on:
  push:
    paths:
      - parser-icu/**
      - .github/workflows/tests-parser-icu.yml
      - .github/workflows/tests.yml
  workflow_dispatch:

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
    with:
      package: parser-icu
